export default {
  // htmlFontSize: 16,
  // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
  // fontSize: 14,
  // fontWeightLight: 300,
  // fontWeightRegular: 400,
  // fontWeightMedium: 500,
  // fontWeightBold: 700,
  h1: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: '2rem',
    lineHeight: 1.25,
    letterSpacing: '0.01em',
  },
  h2: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: '1.334rem',
    lineHeight: 1,
    letterSpacing: '0.01em',
  },
  h3: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    fontSize: '1.25rem',
    lineHeight: 1.4,
    letterSpacing: '0.01em',
  },
  // h4: {
  //   fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
  //   fontWeight: 400,
  //   fontSize: '2.125rem',
  //   lineHeight: 1.17,
  //   letterSpacing: '0.00735em',
  // },
  // h5: {
  //   fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
  //   fontWeight: 400,
  //   fontSize: '1.5rem',
  //   lineHeight: 1.1667,
  //   letterSpacing: '0em',
  // },
  // h6: {
  //   fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
  //   fontWeight: 500,
  //   fontSize: '1.25rem',
  //   lineHeight: 1.15,
  //   letterSpacing: '0.0075em',
  // },
  subtitle1: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    // fontSize: '1rem',
    // lineHeight: 1.1875,
    letterSpacing: '0.02em',
  },
  subtitle2: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 500,
    // fontSize: '0.875rem',
    lineHeight: 1.143,
    letterSpacing: '0.02em',
  },
  body1: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    // fontSize: '1rem',
    // lineHeight: 1.1875,
    letterSpacing: '0.02em',
  },
  body2: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    // fontSize: '0.875rem',
    // lineHeight: 1.1429,
    letterSpacing: '0.02em',
  },
  button: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 500,
    // fontSize: '0.875rem',
    lineHeight: 1.143,
    letterSpacing: '0.02em',
    // textTransform: 'none',
  },
  caption: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    // fontSize: '0.75rem',
    lineHeight: 1.334,
    letterSpacing: '0.02em',
  },
  overline: {
    // fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    // fontWeight: 400,
    fontSize: '0.625rem',
    lineHeight: 1.2,
    letterSpacing: '0.096em',
    // textTransform: 'uppercase',
  },
};
